### ISSUE TITLE
Why there is no option available to reenroll a certificate with a CSR as an argument?

### ISSUE THREAD

**Issue by chicoze** [cisco/libest#90]
Hello.
I want to re-enroll a certificate but I want to sign CSR myself because I'm using a Secure Element from NXP.
I was looking into the API from estclient and you only provide a this function to re-enroll: 
est_client_reenroll(ectx, client_cert_dup, &pkcs7_len, client_priv_key);

**Comment by csosto-pk** [comment]
Hi @chicoze , 

> est_client_reenroll (EST_CTX *ctx, X509 *cert, int *pkcs7_len, EVP_PKEY *priv_key) 

uses the cert we want to reenroll and the corresponding private key to generate a csr and sign it with that key. 

If you wanted to fee it just a signed csr and not build it then you would need to create a new API call that passes the EST_CTX nd the signed csr similar to how lines 467-477 read a csr and pass it to the enrollment. So practically you would need a new API in the library which does not exist right now. 

Note that you could still use 
> est_client_enroll_csr()

with your CSR since a re-enroll is practically an enrollment with the same CSR.

**Comment by chicoze** [comment]
Hi @csosto-pk .
Thanks for the reply. 

I don't understand one thing: to re-enroll, I have to use the same CSR that I used before?
I can't generate a new CSR with the same information as the one before?

**Comment by csosto-pk** [comment]
> I don't understand one thing: to re-enroll, I have to use the same CSR that I used before?
You don't have to. 

> I can't generate a new CSR with the same information as the one before?

You can. 

Theoretically speaking a re-enroll enrolls the same public key/cert for the second time and an enroll enrolls a new key for the first time. But in practice you can re-enroll a new or an old CSR with a new or an old public key in it.
